main:
  method: 'get'
  path: ~
  controller: App\Controller\MovieController
  action: index
show:
    method: 'get'
    path: 'show/{id}'
    controller: App\Controller\MovieController
    action: show

