main:
  method: 'get'
  path: ~
  controller: App\Controller\MovieController
  action: index
show:
    method: 'get'
    path: 'show/{id}'
    controller: App\Controller\MovieController
    action: show
updateLike:
  method: 'get'
  path: 'updateLike/{id}'
  controller: App\Controller\MovieController
  action: updateLike

